//==============================================================
// Module      : fft_top
// Project     : Streaming FFT Accelerator
// Author      : Shreenidhi Inamadar
//
// Description:
// Top-level module for simplified Streaming FFT Accelerator
//
// Architecture:
//
//      Input (serial, 1 sample/cycle)
//        |
//        v
//   Input FIFOs (real/imag, elastic serial-in staging)
//        |
//        v
//   Parallel register array (N samples)
//        |
//        v
//    FFT Stage 1  --(pipeline reg)-->
//    FFT Stage 2  --(pipeline reg)-->
//    FFT Stage 3  --(pipeline reg)-->
//        |
//        v
//      Output (serial, 1 sample/cycle)
//
// Each fft_stage is unchanged from its original form: N/2
// parallel butterflies, always pairing index i with i+N/2,
// one shared twiddle constant per stage (broadcast to all N/2
// butterflies). This means stages 2 and 3 are NOT a
// textbook-correct FFT recursion (that would need a smaller
// pairing stride and per-butterfly twiddle values at each
// stage) -- kept intentionally simple/unchanged per project
// scope (educational, not production FFT IP).
//
//==============================================================

module fft_top #(
    parameter WIDTH = 16,
    parameter DEPTH = 16,
    parameter N = 8
)(
    input logic clk,
    input logic rst_n,
    input logic start,

    //-----------------------------
    // Input Stream
    //-----------------------------

    input logic signed [WIDTH-1:0] in_real,
    input logic signed [WIDTH-1:0] in_imag,

    //-----------------------------
    // Output Stream
    //-----------------------------

    output logic signed [WIDTH-1:0] out_real,
    output logic signed [WIDTH-1:0] out_imag,

    //-----------------------------
    // Status
    //-----------------------------

    output logic busy,
    output logic done,
    output logic out_valid
);

    //----------------------------------------------------------
    // Controller Signals
    //----------------------------------------------------------

    logic fifo_wr_en;
    logic fifo_rd_en;

    logic butterfly_en;
    logic pipeline_en;

    logic feedback_sel;

    logic valid;

    logic [$clog2($clog2(N))-1:0] stage;

    // butterfly_en / feedback_sel / stage are generated by the
    // controller but not consumed by this simplified fixed
    // 3-stage cascade datapath -- they're vestiges of a
    // resource-shared/streaming variant this project doesn't
    // implement. Left connected (declared) for interface
    // stability, intentionally unused below.

    fft_controller #(
        .N(N)
    ) u_controller (

        .clk(clk),
        .rst_n(rst_n),
        .start(start),

        .busy(busy),
        .done(done),
        .valid(valid),

        .fifo_wr_en(fifo_wr_en),
        .fifo_rd_en(fifo_rd_en),

        .butterfly_en(butterfly_en),
        .pipeline_en(pipeline_en),

        .feedback_sel(feedback_sel),

        .stage(stage)

    );

    //----------------------------------------------------------
    // Input FIFOs (serial-in elastic staging, real / imag)
    //----------------------------------------------------------

    logic signed [WIDTH-1:0] fifo_out_real;
    logic signed [WIDTH-1:0] fifo_out_imag;

    fifo #(
        .WIDTH(WIDTH),
        .DEPTH(DEPTH)
    ) u_in_fifo_real (
        .clk(clk),
        .rst_n(rst_n),
        .wr_en(fifo_wr_en),
        .rd_en(fifo_rd_en),
        .data_in(in_real),
        .data_out(fifo_out_real),
        .full(),
        .empty()
    );

    fifo #(
        .WIDTH(WIDTH),
        .DEPTH(DEPTH)
    ) u_in_fifo_imag (
        .clk(clk),
        .rst_n(rst_n),
        .wr_en(fifo_wr_en),
        .rd_en(fifo_rd_en),
        .data_in(in_imag),
        .data_out(fifo_out_imag),
        .full(),
        .empty()
    );

    //----------------------------------------------------------
    // Serial-to-Parallel Unload
    //
    // fifo.sv registers its read data (one cycle of latency per
    // pop), so the capture below is driven by fifo_rd_en/pointer
    // delayed by one cycle relative to the pop request itself.
    //----------------------------------------------------------

    logic [$clog2(N+1)-1:0] unload_ptr;
    logic                   fifo_rd_en_d1;
    logic [$clog2(N+1)-1:0] unload_ptr_d1;

    always_ff @(posedge clk or negedge rst_n)
    begin
        if(!rst_n)
            unload_ptr <= '0;
        else if(!busy)
            unload_ptr <= '0;
        else if(fifo_rd_en)
            unload_ptr <= unload_ptr + 1'b1;
    end

    always_ff @(posedge clk or negedge rst_n)
    begin
        if(!rst_n)
        begin
            fifo_rd_en_d1 <= 1'b0;
            unload_ptr_d1 <= '0;
        end
        else
        begin
            fifo_rd_en_d1 <= fifo_rd_en;
            unload_ptr_d1 <= unload_ptr;
        end
    end

    logic signed [WIDTH-1:0] stage_in_real [0:N-1];
    logic signed [WIDTH-1:0] stage_in_imag [0:N-1];

    always_ff @(posedge clk or negedge rst_n)
    begin
        if(!rst_n)
        begin
            stage_in_real <= '{default:'0};
            stage_in_imag <= '{default:'0};
        end
        else if(fifo_rd_en_d1)
        begin
            stage_in_real[unload_ptr_d1] <= fifo_out_real;
            stage_in_imag[unload_ptr_d1] <= fifo_out_imag;
        end
    end

    //----------------------------------------------------------
    // Twiddle Broadcast
    //
    // Each stage keeps a single shared twiddle constant
    // (unchanged from the original design), broadcast into the
    // N/2-wide array port fft_stage expects.
    //----------------------------------------------------------

    localparam signed [WIDTH-1:0] TW1_REAL = 16'sd32767;
    localparam signed [WIDTH-1:0] TW1_IMAG = 16'sd0;

    localparam signed [WIDTH-1:0] TW2_REAL = 16'sd23170;
    localparam signed [WIDTH-1:0] TW2_IMAG = -16'sd23170;

    localparam signed [WIDTH-1:0] TW3_REAL = 16'sd0;
    localparam signed [WIDTH-1:0] TW3_IMAG = -16'sd32767;

    logic signed [WIDTH-1:0] tw1_real [0:(N/2)-1];
    logic signed [WIDTH-1:0] tw1_imag [0:(N/2)-1];
    logic signed [WIDTH-1:0] tw2_real [0:(N/2)-1];
    logic signed [WIDTH-1:0] tw2_imag [0:(N/2)-1];
    logic signed [WIDTH-1:0] tw3_real [0:(N/2)-1];
    logic signed [WIDTH-1:0] tw3_imag [0:(N/2)-1];

    genvar gi;
    generate
        for(gi = 0; gi < N/2; gi = gi + 1)
        begin : GEN_TWIDDLE_BROADCAST
            assign tw1_real[gi] = TW1_REAL;
            assign tw1_imag[gi] = TW1_IMAG;
            assign tw2_real[gi] = TW2_REAL;
            assign tw2_imag[gi] = TW2_IMAG;
            assign tw3_real[gi] = TW3_REAL;
            assign tw3_imag[gi] = TW3_IMAG;
        end
    endgenerate

    //----------------------------------------------------------
    // FFT Stage 1 (+ pipeline register)
    //----------------------------------------------------------

    logic signed [WIDTH-1:0] stage1_comb_real [0:N-1];
    logic signed [WIDTH-1:0] stage1_comb_imag [0:N-1];
    logic signed [WIDTH-1:0] stage1_reg_real  [0:N-1];
    logic signed [WIDTH-1:0] stage1_reg_imag  [0:N-1];

    fft_stage #(
        .WIDTH(WIDTH),
        .N(N)
    ) u_stage1 (
        .real_in(stage_in_real),
        .imag_in(stage_in_imag),
        .tw_real(tw1_real),
        .tw_imag(tw1_imag),
        .real_out(stage1_comb_real),
        .imag_out(stage1_comb_imag)
    );

    always_ff @(posedge clk or negedge rst_n)
    begin
        if(!rst_n)
        begin
            stage1_reg_real <= '{default:'0};
            stage1_reg_imag <= '{default:'0};
        end
        else if(pipeline_en)
        begin
            stage1_reg_real <= stage1_comb_real;
            stage1_reg_imag <= stage1_comb_imag;
        end
    end

    //----------------------------------------------------------
    // FFT Stage 2 (+ pipeline register)
    //----------------------------------------------------------

    logic signed [WIDTH-1:0] stage2_comb_real [0:N-1];
    logic signed [WIDTH-1:0] stage2_comb_imag [0:N-1];
    logic signed [WIDTH-1:0] stage2_reg_real  [0:N-1];
    logic signed [WIDTH-1:0] stage2_reg_imag  [0:N-1];

    fft_stage #(
        .WIDTH(WIDTH),
        .N(N)
    ) u_stage2 (
        .real_in(stage1_reg_real),
        .imag_in(stage1_reg_imag),
        .tw_real(tw2_real),
        .tw_imag(tw2_imag),
        .real_out(stage2_comb_real),
        .imag_out(stage2_comb_imag)
    );

    always_ff @(posedge clk or negedge rst_n)
    begin
        if(!rst_n)
        begin
            stage2_reg_real <= '{default:'0};
            stage2_reg_imag <= '{default:'0};
        end
        else if(pipeline_en)
        begin
            stage2_reg_real <= stage2_comb_real;
            stage2_reg_imag <= stage2_comb_imag;
        end
    end

    //----------------------------------------------------------
    // FFT Stage 3 (+ result register)
    //----------------------------------------------------------

    logic signed [WIDTH-1:0] stage3_comb_real [0:N-1];
    logic signed [WIDTH-1:0] stage3_comb_imag [0:N-1];
    logic signed [WIDTH-1:0] result_real      [0:N-1];
    logic signed [WIDTH-1:0] result_imag      [0:N-1];

    fft_stage #(
        .WIDTH(WIDTH),
        .N(N)
    ) u_stage3 (
        .real_in(stage2_reg_real),
        .imag_in(stage2_reg_imag),
        .tw_real(tw3_real),
        .tw_imag(tw3_imag),
        .real_out(stage3_comb_real),
        .imag_out(stage3_comb_imag)
    );

    always_ff @(posedge clk or negedge rst_n)
    begin
        if(!rst_n)
        begin
            result_real <= '{default:'0};
            result_imag <= '{default:'0};
        end
        else if(pipeline_en)
        begin
            result_real <= stage3_comb_real;
            result_imag <= stage3_comb_imag;
        end
    end

    //----------------------------------------------------------
    // Parallel-to-Serial Drain
    //----------------------------------------------------------

    logic [$clog2(N)-1:0] drain_ptr;

    always_ff @(posedge clk or negedge rst_n)
    begin
        if(!rst_n)
            drain_ptr <= '0;
        else if(!busy)
            drain_ptr <= '0;
        else if(valid)
            drain_ptr <= drain_ptr + 1'b1;
    end

    assign out_real  = result_real[drain_ptr];
    assign out_imag  = result_imag[drain_ptr];
    assign out_valid = valid;

endmodule
